### ISSUE TITLE
Fix cargo test

### ISSUE THREAD

**Issue by ignatenkobrain** [rust-x-bindings/rust-xcb#60]
```rust
---- src/xproto.rs - xproto::GC_PLANE_MASK (line 598) stdout ----
error: expected one of `!`, `)`, `,`, `.`, `::`, `?`, `{`, or an operator, found `FUNC`
 --> src/xproto.rs:599:7
  |
3 | ((src FUNC dst) AND plane-mask) OR (dst AND (NOT plane-mask))
  |       ^^^^ expected one of 8 possible tokens here

thread 'src/xproto.rs - xproto::GC_PLANE_MASK (line 598)' panicked at 'couldn't compile the test', src/librustdoc/test.rs:321:13

---- src/ffi/xproto.rs - ffi::xproto::XCB_GC_PLANE_MASK (line 3654) stdout ----
error: expected one of `!`, `)`, `,`, `.`, `::`, `?`, `{`, or an operator, found `FUNC`
 --> src/ffi/xproto.rs:3655:7
  |
3 | ((src FUNC dst) AND plane-mask) OR (dst AND (NOT plane-mask))
  |       ^^^^ expected one of 8 possible tokens here

thread 'src/ffi/xproto.rs - ffi::xproto::XCB_GC_PLANE_MASK (line 3654)' panicked at 'couldn't compile the test', src/librustdoc/test.rs:321:13
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

---- src/base.rs - base::pack_bitfield (line 747) stdout ----
error[E0425]: cannot find value `Oxffffffff` in this scope
  --> src/base.rs:755:13
   |
11 |             Oxffffffff,
   |             ^^^^^^^^^^ not found in this scope

error[E0425]: cannot find function `pack_bitfield` in this scope
  --> src/base.rs:760:16
   |
16 |     assert_eq!(pack_bitfield(&mut values), ffi_values);
   |                ^^^^^^^^^^^^^ not found in this scope
help: possible candidates are found in other modules, you can import them into scope
   |
3  | use xcb::base::pack_bitfield;
   |
3  | use xcb::pack_bitfield;
   |

thread 'src/base.rs - base::pack_bitfield (line 747)' panicked at 'couldn't compile the test', src/librustdoc/test.rs:321:13


failures:
    src/base.rs - base::pack_bitfield (line 747)
    src/ffi/xproto.rs - ffi::xproto::XCB_GC_PLANE_MASK (line 3654)
    src/xproto.rs - xproto::GC_PLANE_MASK (line 598)
```

**Comment by infinity0** [comment]
Same on Debian and everywhere else - a normal call to `cargo test` fails in exactly the same way as described above.

**Comment by rtbo** [comment]
I do not use `cargo test`.
At the moment the only tests available are whether the examples compile fine or not.
This is tested with `scripts/test_examples.sh`

**Comment by infinity0** [comment]
Would it possible to fix `cargo test`? It is effectively an API that distro packagers use to ensure we've done our side of the packaging correctly, and it is tedious to add exceptions for every single crates where the tests are not expected to work.

These particular fixes also look like it is simply that the doc comments are somehow being mis-interpreted as test code to be executed. Perhaps it would be sufficient to wrap them in <code>\```ignore</code> and <code>\```</code>

**Comment by rtbo** [comment]
[v1.0.0](https://crates.io/crates/xcb/1.0.0) is released.
